# Generated by Django 3.1.7 on 2021-04-18 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader_product',
            name='trader_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.trader_bill'),
        ),
    ]
