# Generated by Django 3.0.2 on 2021-05-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210426_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pre_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
