# Generated by Django 3.1.7 on 2021-04-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210418_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader_product',
            name='restored_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
