# Generated by Django 3.1.7 on 2021-04-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_trader_product_restored_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_product',
            name='total_quantity_fixed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trader_product',
            name='total_quantity_fixed',
            field=models.IntegerField(default=0),
        ),
    ]
