# Generated by Django 3.0.2 on 2021-05-13 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_customer_pre_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader_product',
            name='come_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Trader_Product'),
        ),
    ]
