# Generated by Django 3.1.7 on 2021-04-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20210418_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader_product',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='trader_product',
            name='total_cost_old',
        ),
    ]
