# Generated by Django 3.1.7 on 2021-04-18 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20210418_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader_product',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='trader_product',
            name='production_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
