# Generated by Django 3.1.7 on 2021-04-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_trader_bill_come_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader_product',
            name='line_type',
            field=models.IntegerField(default=0),
        ),
    ]
