# Generated by Django 3.1.7 on 2021-04-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20210419_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point_product',
            old_name='quantity_new',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='point_product',
            old_name='quantity_packet_new',
            new_name='quantity_packet',
        ),
        migrations.RemoveField(
            model_name='point_product',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='point_product',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='point_product',
            name='production_date',
        ),
        migrations.RemoveField(
            model_name='point_product',
            name='sold_quantity',
        ),
    ]
