# Generated by Django 3.1.7 on 2021-04-21 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20210421_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_to_point_product',
            name='point_product',
        ),
        migrations.AddField(
            model_name='point_product',
            name='trader_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.trader_product'),
        ),
        migrations.AddField(
            model_name='store_to_point_product',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.point'),
        ),
    ]
