# Generated by Django 3.1.7 on 2021-04-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_store_to_point_product_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_to_point_product',
            name='trader_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.trader_product'),
        ),
    ]
