# Generated by Django 3.1.7 on 2021-04-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20210421_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='total_money',
        ),
        migrations.RemoveField(
            model_name='point',
            name='total_money_raw',
        ),
    ]
