# Generated by Django 3.1.7 on 2021-04-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20210421_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_to_point_product',
            name='total_quantity',
        ),
    ]
