# Generated by Django 3.1.7 on 2021-04-22 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_remove_store_to_point_product_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_to_point_product',
            name='to_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='To_Point', to='content.point'),
        ),
        migrations.AlterField(
            model_name='store_to_point_product',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Store_To_Point_Product', to='content.point'),
        ),
    ]
