# Generated by Django 3.1.7 on 2021-04-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20210422_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point_product_sellings',
            old_name='quantity_new',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='point_product_sellings',
            old_name='quantity_packet_new',
            new_name='quantity_packet',
        ),
        migrations.RemoveField(
            model_name='point_product_sellings',
            name='come_from_line_id',
        ),
        migrations.RemoveField(
            model_name='point_product_sellings',
            name='money_quantity_buy',
        ),
        migrations.RemoveField(
            model_name='point_product_sellings',
            name='money_quantity_sell',
        ),
        migrations.RemoveField(
            model_name='point_product_sellings',
            name='restored_amount_cost',
        ),
        migrations.RemoveField(
            model_name='point_product_sellings',
            name='restored_amount_cost_ad',
        ),
        migrations.RemoveField(
            model_name='point_product_sellings',
            name='restored_amount_cost_buy',
        ),
        migrations.RemoveField(
            model_name='point_product_sellings',
            name='unit_sell_price',
        ),
        migrations.AddField(
            model_name='point_product_sellings',
            name='total_quantity_fixed',
            field=models.IntegerField(default=0),
        ),
    ]
