# Generated by Django 3.1.7 on 2021-04-22 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20210422_2314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acumulate_payment',
        ),
        migrations.RemoveField(
            model_name='month_total_calculation',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='point_product_store_restore',
            name='Point',
        ),
        migrations.RemoveField(
            model_name='point_product_store_restore',
            name='product',
        ),
        migrations.RemoveField(
            model_name='total_point_product',
            name='Point',
        ),
        migrations.RemoveField(
            model_name='total_point_product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='total_point_product',
            name='sub_product',
        ),
        migrations.RemoveField(
            model_name='trader_product_restore',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='trader_product_restore',
            name='product',
        ),
        migrations.RemoveField(
            model_name='trader_product_restore',
            name='trader',
        ),
        migrations.DeleteModel(
            name='Day_Payment_Line',
        ),
        migrations.DeleteModel(
            name='Month_Total_Calculation',
        ),
        migrations.DeleteModel(
            name='Point_Product_Store_Restore',
        ),
        migrations.DeleteModel(
            name='Total_Point_Product',
        ),
        migrations.DeleteModel(
            name='Trader_Product_Restore',
        ),
    ]
