# Generated by Django 3.1.7 on 2021-04-23 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_auto_20210423_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_product_sellings',
            name='come_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.point_product_sellings'),
        ),
        migrations.AddField(
            model_name='point_product_sellings',
            name='unit_sell_price',
            field=models.IntegerField(default=0),
        ),
    ]
