# Generated by Django 3.1.7 on 2021-04-23 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_auto_20210423_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='given_money',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='total_money',
        ),
    ]
