# Generated by Django 3.0.2 on 2021-04-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_auto_20210424_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point_product_sellings',
            name='unit_sell_price',
            field=models.FloatField(default=0),
        ),
    ]
